version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./fe-react
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000

  api:
    build:
      context: ./BEGoGin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/MLMW?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/app/main"]
    # entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]
  
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=MLMW
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d MLMW'"]
      interval: 10s
      timeout: 3s
      retries: 3
