version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./fe-react
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
  
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=MLMW

  api:
    build:
      context: ./BEGoGin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/MLMW?sslmode=disable
    depends_on:
      - postgres 
    command: ["/app/main"]
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]
