version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=MLMW
    # volumes:
    #   - data-volume:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/MLMW?sslmode=disable
    depends_on:
      - postgres
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: infras
    #       target: /app/infras
    #       ignore:
    #         - dto/
            
    command: ["/app/main"]
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"]